# SwiftLint Configuration for BlackboxPlayer

# Paths to include during linting
included:
  - BlackboxPlayer

# Paths to ignore during linting
excluded:
  - Pods
  - .build
  - DerivedData
  - BlackboxPlayer.xcodeproj
  - BlackboxPlayer.xcworkspace

# Disable specific rules
disabled_rules:
  - trailing_whitespace
  - todo                            # TODO 주석 허용 (개발 중)
  - orphaned_doc_comment            # Doxygen 스타일 주석 허용

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Customizable rules
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

nesting:
  type_level:
    warning: 2
    error: 3

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

# Reporter type
reporter: "xcode"
