name: BlackboxPlayer
options:
  bundleIdPrefix: com.blackboxplayer
  deploymentTarget:
    macOS: "12.0"
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  BlackboxPlayer:
    type: application
    platform: macOS
    sources:
      - path: BlackboxPlayer
        excludes:
          - "**/*.md"
          - "Tests/**"
    settings:
      base:
        INFOPLIST_FILE: BlackboxPlayer/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.blackboxplayer.app
        CODE_SIGN_ENTITLEMENTS: BlackboxPlayer/Resources/BlackboxPlayer.entitlements
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_OBJC_BRIDGING_HEADER: BlackboxPlayer/Utilities/BridgingHeader.h
        HEADER_SEARCH_PATHS: /opt/homebrew/Cellar/ffmpeg/8.0_1/include
        LIBRARY_SEARCH_PATHS: /opt/homebrew/Cellar/ffmpeg/8.0_1/lib
        OTHER_LDFLAGS: -lavformat -lavcodec -lswscale -lavutil -lswresample
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      configs:
        Debug:
          OTHER_SWIFT_FLAGS: -DDEBUG
        Release:
          OTHER_SWIFT_FLAGS: -O
    scheme:
      testTargets:
        - BlackboxPlayerTests
      gatherCoverageData: true

  BlackboxPlayerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - BlackboxPlayer/Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blackboxplayer.tests
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_OBJC_BRIDGING_HEADER: BlackboxPlayer/Utilities/BridgingHeader.h
        HEADER_SEARCH_PATHS: /opt/homebrew/Cellar/ffmpeg/8.0_1/include
        LIBRARY_SEARCH_PATHS: /opt/homebrew/Cellar/ffmpeg/8.0_1/lib
    dependencies:
      - target: BlackboxPlayer

schemes:
  BlackboxPlayer:
    build:
      targets:
        BlackboxPlayer: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - BlackboxPlayerTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
