name: Build and Test

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
  workflow_dispatch:

env:
  CI: true
  GITHUB_ACTIONS: true

jobs:
  build:
    name: Build ${{ matrix.configuration }}
    runs-on: macos-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Install Dependencies
      run: |
        brew install xcodegen
        xcodegen --version

    - name: Build and Test
      run: |
        ./scripts/ci-build.sh ${{ matrix.configuration }}

    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: BlackboxPlayer-${{ matrix.configuration }}
        path: build/DerivedData/Build/Products/${{ matrix.configuration }}/BlackboxPlayer.app
        retention-days: 7

    - name: Upload Test Results
      if: matrix.configuration == 'Debug' && success()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: |
          build/TestResults.xcresult
          build/coverage.json
        retention-days: 7

    - name: Upload Coverage Reports
      if: matrix.configuration == 'Debug' && success()
      uses: codecov/codecov-action@v4
      with:
        files: ./build/coverage.json
        fail_ci_if_error: false
        verbose: true

    - name: Upload Build Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.configuration }}
        path: build/*.log
        retention-days: 3

  lint:
    name: Swift Lint
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging || true

  archive:
    name: Create Release Archive
    runs-on: macos-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: [build, lint]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Dependencies
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen

    - name: Create Archive
      run: |
        mkdir -p build/Archives
        xcodebuild \
          -project BlackboxPlayer.xcodeproj \
          -scheme BlackboxPlayer \
          -configuration Release \
          -archivePath build/Archives/BlackboxPlayer.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          clean archive

    - name: Upload Archive
      uses: actions/upload-artifact@v4
      with:
        name: BlackboxPlayer-Archive
        path: build/Archives/BlackboxPlayer.xcarchive
        retention-days: 30
