name: Build and Test

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
  workflow_dispatch:

env:
  XCODE_VERSION: '15.0'
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build:
    name: Build and Test
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Install Dependencies
      run: |
        brew install xcodegen swiftlint

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Build Project
      run: |
        xcodebuild clean build \
          -project BlackboxPlayer.xcodeproj \
          -scheme BlackboxPlayer \
          -configuration Debug \
          -destination 'platform=macOS,arch=arm64' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    - name: Run Tests
      run: |
        xcodebuild test \
          -project BlackboxPlayer.xcodeproj \
          -scheme BlackboxPlayer \
          -configuration Debug \
          -destination 'platform=macOS,arch=arm64' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    - name: Run SwiftLint
      run: |
        swiftlint lint --reporter github-actions-logging || true

    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v4
      if: success()
      with:
        fail_ci_if_error: false
        verbose: true

  lint:
    name: Swift Lint
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint lint --strict
